# Generated by Django 4.1.2 on 2022-11-28 15:41

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('salary', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('cnic', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=30)),
                ('imgs', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to='')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registration.role')),
            ],
        ),
    ]
