# Generated by Django 4.1.2 on 2022-11-28 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Violations', '0002_alter_violations_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violations',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2022, 11, 28, 21, 16, 9, 599336)),
        ),
        migrations.AlterField(
            model_name='violations',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2022, 11, 28, 21, 16, 9, 599336)),
        ),
    ]
