# Generated by Django 4.1.2 on 2022-11-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Violations', '0003_alter_violations_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='insensity',
            field=models.CharField(choices=[('High', 'Critical Violations'), ('Medium', 'Medium Violations'), ('Low', 'Non-Critical Violations')], max_length=30),
        ),
        migrations.AlterField(
            model_name='violations',
            name='end_time',
            field=models.CharField(default='14:11:52', max_length=20),
        ),
        migrations.AlterField(
            model_name='violations',
            name='start_time',
            field=models.CharField(default='14:11:52', max_length=20),
        ),
        migrations.AlterField(
            model_name='zone',
            name='description',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
