# Generated by Django 4.1.2 on 2022-12-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Violations', '0005_alter_violations_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violations',
            name='end_time',
            field=models.CharField(default='10:16:22', max_length=20),
        ),
        migrations.AlterField(
            model_name='violations',
            name='start_time',
            field=models.CharField(default='10:16:22', max_length=20),
        ),
    ]
